### ISSUE TITLE
Support for sh:closed

### ISSUE THREAD

**Issue by abrokenjester** [eclipse-rdf4j/rdf4j#1112]
_From @hmottestad on March 27, 2018 11:49_

Add support for sh:closed

sh:closed is quite hard to validate. Essentially it allows someone to specify that a node of type X is only allowed to use certain predicates. In other words, any predicates on a node that have not been used when evaluating a SHACL rule, are violations.

Possible way to handle this is to collect all statements in a hashmap that have been used for evaluating  rules, or to add a field to the statements to keep track of if they were validated or not.

sh:closed might also open up some new ways of optimizing validation.

Related feature to implement: sh:ignoredProperties

_Copied from original issue: eclipse/rdf4j-storage#61_

**Comment by jeenbroekstra** [comment]
@hmottestad this still relevant?

**Comment by hmottestad** [comment]
Yes, this is still not implemented.
