### ISSUE TITLE
Add GeoSPARQL vocabulary constants

### ISSUE THREAD

**Issue by abrokenjester** [eclipse-rdf4j/rdf4j#4505]
### Discussed in https://github.com/eclipse/rdf4j/discussions/4504

<div type='discussions-op-text'>

<sup>Originally posted by **luisramosbosch** April 11, 2023</sup>
Dear All, 

I am trying to develop a minimum example in geosparql, following this documentation:

https://rdf4j.org/documentation/programming/geosparql/

I have the idea, that I should be able to build the example using code, but when I tried to do it, 
I found some method (object property, and class defition) I would expect were no present,
like geo:hasGeometry or geof:Point, which would be neccesary to build the model of the example.

model.add(eiffelTower, GEO.hasGeometry, coordinateset );
model.add(coordinateset, RDF.TYPE, GEOF.Point );

Could you tell me if building the model from code is possible?, or if I have to edit the model somewhere else, 
and use rdf4j only for querying?.

Best regards

Luis Ramos
</div>

**Comment by hmottestad** [comment]
Fixed by: @linnaung
