### ISSUE TITLE
SHACL - Blank node IDs should be preserved for remote validation reports

### ISSUE THREAD

**Issue by hmottestad** [eclipse-rdf4j/rdf4j#4622]
Blank node IDs should be preserved for remote validation reports because users need to be able to look up data in the repository based on the validation report model. 

One typical use case is for retrieving the full SHACL Shape from the repository. PropertyShape(s) are usually blank nodes, and when the report refers to a PropertyShape it uses the blank nodes. 

Another use case is where the validation report refers to a blank node from the users data that is causing the validation violation.

**Comment by abrokenjester** [comment]
Can you elaborate on _why_ this is necessary?

**Comment by hmottestad** [comment]
> Can you elaborate on _why_ this is necessary? 
> 
> 

I updated the issue.
