### ISSUE TITLE
Transaction Hang and Memory Lock Issue Causing System Freeze

### ISSUE THREAD

**Issue by NordilJ** [eclipse-rdf4j/rdf4j#4740]
### Current Behavior

When a transaction successfully acquires memory store locks, we have observed a scenario where these locks are not released properly by a terminated thread. As a result, subsequent transactions attempting to acquire the same locks become suspended, leading to a system hang. This issue seems to be triggered during the execution of the "flush()" method within the "SailSourceBranch" class. While exceptions encountered during this method are appropriately captured by the error-handling mechanism, the associated "MemorySailSink" state is reset, without a controlled shutdown procedure.

### Expected Behavior

We anticipate that memory store locks acquired by a terminated thread should be promptly released, enabling other transactions to acquire the locks without suspension. Additionally, we expect that exceptions encountered within the "flush()" method should trigger a controlled shutdown procedure for the relevant "MemorySailSink" instance.

### Steps To Reproduce

No specific steps to reproduce since this is flaky, and not examine often. More about the issue can be found at:

https://ontotext.atlassian.net/browse/GDB-8271 

### Version

4.3.3

### Are you interested in contributing a solution yourself?

None

**Comment by hmottestad** [comment]
I didn't see that you had made an issue for this already. I fixed this in  https://github.com/eclipse-rdf4j/rdf4j/issues/4784
