### ISSUE TITLE
Scoping issue with undefined variable in FILTER

### ISSUE THREAD

**Issue by fkleedorfer** [eclipse-rdf4j/rdf4j#4769]
### Current Behavior

We use the memory store for integration tests. The store is instantiated once and  then data is added to and removed from it, with calls to commit() after each batch of changes.

We noticed intermittent test failures (expected query results are sometimes not returned). We isolated the failing tests and let one of them repeat until failure. Observation: it reproducibly succeeds 19 times and then fails. 
Adding a `Thread.sleep(x)` at the beginning of the test increases the number of times it succeeds when x > 300. at x > 1000 the failures seem to go away completely.

I put a breakpoint at MemorySailStore.java:638 (at beginning of the `flush()` method), which, after several calls during the instantiation of the store (where we add some background data), is hit once every time the test is executed. At that point, if I call the `cleanSnapshots()` method every 10 or so test runs, the failure never occurs. 

Without intervention throught the thread debugger, the `cleanSnapshots()` method never gets called before the test fails in execution 20, roughly 1.8 seconds after the first invocation of the test. 

When set the sleep timeout mentioned above to 1000 millis, the `cleanSnapshots()` methods does reproducibly get called every few test runs, and the test failure never occurs.

Here is the query that yields results normally, and yields nothing under the circumstances described.
```
PREFIX mms: <https://mms.researchstudio.at/mms#>
PREFIX s: <http://schema.org/>
SELECT DISTINCT ?entityId ?entityType ?entityDateCreated ?entityDateModified
WHERE { ?entityId <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?entityType ;
    s:dateCreated ?entityDateCreated ;
    s:dateModified ?entityDateModified .
?entityId s:editor ?entityEditor .
{ ?entityId <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?entityType .
FILTER ( ( ?entityEditor NOT IN ( "ax533d70-0cd5-4425-beda-080c56b8b820" ) ) ) }
FILTER ( ?entityType IN ( mms:Standard, mms:Project, mms:Organization, mms:Feature, mms:FeatureGroup, mms:PropertySet, mms:Mapping ) ) }
ORDER BY DESC( ?entityDateModified )
```

At the point of failing, the stores' statementList has 40692 statements, including those from old snapshots, and 24844 'null' slots, the size of the array is 65536. the activeConnections Map only has one connection (the one we are using for the tests).

I don't see any obvious source of the change in query evaluation, but I also fail to understand why we would keep old snapshots around after a commit, if we have no other connections with pending data changes.

### Expected Behavior

The memory store should allow adding and removing data with commits in between and consistenly return consistent query results until the end of time, not just 1.8 seconds, or 20 test runs.

### Version

4.3.6 (edit: 5.0.0-M1 as well, and 4.2.0, too)

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by fkleedorfer** [comment]
The workaround we'll use until this is fixed is to run cleanSnapshots() each time after inserting the test data: 
```
Sail sail = repository.getSail();
                        Class<?> sailClass = sail.getClass();
                        try {
                            Field storeField = sailClass.getDeclaredField("store");
                            if (storeField != null) {
                                storeField.setAccessible(true);
                                Object storeObj = storeField.get(sail);
                                Method cleanSnapshotsMethod = storeObj.getClass().getDeclaredMethod("cleanSnapshots");
                                if (cleanSnapshotsMethod != null) {
                                    cleanSnapshotsMethod.setAccessible(true);
                                    cleanSnapshotsMethod.invoke(storeObj);
                                }
                            }
                        } catch (Exception e) {
                            throw new RuntimeException("error preparing test data", e);
                        }
```

**Comment by hmottestad** [comment]
What is your failure? OOM?

**Comment by fkleedorfer** [comment]
No, a test assertion failure. The query is expected to return 63 results, and in run 20, it returns 0.

The data returned via the connection is always the same (apart from bnode labels), including in run 20.

I debug-stepped into the query evaluation, where it becomes impossible for me to see a difference in how the query evaluates in the test run that fails, because it is a tree of easily 5 layers of iterators.

**Comment by hmottestad** [comment]
> No, a test assertion failure. The query is expected to return 63 results, and in run 20, it returns 0.
> 

Well that's not good.

The data structure for the memory store is a lock free array backed list-like implementation. The snapshot cleanup is async. The data structure only supports a single thread for cleanup (deletion), but supports multiple threads for inserts and reads.

Since you're test is fine when your call the cleanup method directly, or when you slow down the test, then I wonder if there is an issue with how the data structure handles the growing of the underlying array. 

It would be very helpful if you could provide some code that I can use to reproduce the issue. It could also be platform dependent, are you on Intel, AMD, aarch64, or something else?

**Comment by fkleedorfer** [comment]
My platform is Intel.

Here is a repo for reproducing the problem: https://github.com/fkleedorfer/rdf4j-bugs/

run `mvn install` to reproduce.

Happy to contribute this repo for future similar situations - now that we can have multiple repos in the rdf4j github.

**Comment by hmottestad** [comment]
Thanks @fkleedorfer 

I was able to reproduce the issue and I have some good news and some bad news. The good news is that it doesn't seem to have anything to do with any of the internals of the MemoryStore.

The bad news is that the issue is related to how the query is optimized. As the underlying arrays in the MemoryStore grow they cause the query optimization estimates to change. By running the snapshot cleanup method periodically you managed to stop the arrays from growing too large, so that's why it mitigated the issue.

Here are the two different query plans. Left is the query plan for the failed query, and the right is the one a passing query.

<img width="1686" alt="Screenshot 2023-09-05 at 22 30 57" src="https://github.com/eclipse-rdf4j/rdf4j/assets/797185/11616618-b7f8-4d46-b375-167cb8ae3dff">

**Comment by hmottestad** [comment]
I've tracked it back to this issue here https://github.com/eclipse-rdf4j/rdf4j/issues/3601

When I revert the FilterIterator to before the fix for that issue the query consistently return 0, even for the first run.

**Comment by hmottestad** [comment]
FYI. There also seems to be an issue with the query explanation. It's supposed to track the actual result size of each portion of the query.

**Comment by hmottestad** [comment]
```
PREFIX mms: <https://mms.researchstudio.at/mms#>
PREFIX s: <http://schema.org/>
SELECT DISTINCT ?entityId ?entityType ?entityDateCreated ?entityDateModified
WHERE {

    ?entityId <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?entityType ;
        s:dateCreated ?entityDateCreated ;
        s:dateModified ?entityDateModified .

    ?entityId s:editor ?entityEditor .

    {
        ?entityId <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?entityType .
        FILTER ( ( ?entityEditor NOT IN ( "ax533d70-0cd5-4425-beda-080c56b8b820" ) ) ) 
    }

    FILTER ( ?entityType IN ( mms:Standard, mms:Project, mms:Organization, mms:Feature, mms:FeatureGroup, mms:PropertySet, mms:Mapping ) )
}

ORDER BY DESC( ?entityDateModified )
```

Above is the query that you are using. 

The line with ` FILTER ( ( ?entityEditor NOT IN ( "ax533d70-0cd5-4425-beda-080c56b8b820" ) ) ) ` is within a new scope where `?entityEditor` is not defined. That seems to be the core of the issue.

I tend to think that the old behaviour was correct. Since the SPARQL 1.1 spec says:

> Specifically, FILTERs eliminate any solutions that, when substituted into the expression, either result in an effective boolean value of false or produce an error.

**Comment by fkleedorfer** [comment]
Oops... We got confused with the sparqlbuilder, apparently. Thanks for digging into this!

**Comment by hmottestad** [comment]
I'm glad it's not an issue with the MemoryStore. I've made some tests to reproduce the scoping issue and I've discovered that it's not as simple as reverting the FilterIterator.

**Comment by fkleedorfer** [comment]
Well, thanks again for your help, I rewrote the code that generates the query to not filter on something that's out of scope and the issue went away - just to re-confirm.

I found the rdf4-bugs project useful for reproducing the bug, and I would use it again. It would help save time for the next person in that situation.  Should I transfer ownership to the eclipse-rdf4j org?
