### ISSUE TITLE
RDFa support is being deprecated but is still required

### ISSUE THREAD

**Issue by edwardsph** [eclipse-rdf4j/rdf4j#4779]
### Current Behavior

I'm raising this as a bug since the changes to Rio are going to break existing applications which are currently reporting usage of deprecated code.

It is currently possible to parse RDFa with Rio using https://github.com/semarglproject/semargl-rdf4j as a parser plugin:
```
ParserConfig parserConfig = new ParserConfig();
parserConfig.set(RDFaParserSettings.RDFA_COMPATIBILITY, RDFaVersion.RDFA_1_1);
Model model = Rio.parse(is, "https://example.org", RDFFormat.RDFA,
    parserConfig, SimpleValueFactory.getInstance(), new ParseErrorLogger());
```
See also: https://github.com/eclipse-rdf4j/rdf4j/issues/512

The RDFa settings are now marked as deprecated, to be removed in 5.0 as it was assumed they were not in use: https://github.com/eclipse-rdf4j/rdf4j/pull/4332. 

### Expected Behavior

The RDFa settings may not be used internally but they are used by plugins and deprecating them would prevent this. Please do not deprecate them.

### Version

4.3.6

### Are you interested in contributing a solution yourself?

None

**Comment by hmottestad** [comment]
This is just the RIO settings we are talking about right?

**Comment by edwardsph** [comment]
I believe so. I think it was assumed that because RIO doesn't directly support RDFa then the settings aren't needed but that's forgetting that they are needed when using a 3rd party plugin.

**Comment by hmottestad** [comment]
All the other RIO settings are being consolidated. Do you think the RIO settings for RDFa would still work if we change the namespace?

**Comment by edwardsph** [comment]
I'd have to look at that but why not consolidate them with the others?

**Comment by hmottestad** [comment]
Never mind. I had thought of the sail config. 

The RIO settings aren't IRIs. We can move them to where the other RIO settings have been moved and add a comment referring to this issue here so they don't get deprecated again in the future.

**Comment by edwardsph** [comment]
That would be perfect, thanks

**Comment by edwardsph** [comment]
@hmottestad Please can you add this issue to the milestone list for 5.0.0 so it is not forgotten. Thanks

**Comment by hmottestad** [comment]
If you have a chance it would be very kind if you could make a PR with the changes to remove the deprecation annotation and add a comment explaining that it's still in use referencing this issue.
