### ISSUE TITLE
INSERT .. WHERE with multiple VALUES clauses no longer works (regression)

### ISSUE THREAD

**Issue by vtermanis** [eclipse-rdf4j/rdf4j#4815]
### Current Behavior

When performing an `INSERT .. WHERE` with more than one `VALUES` clause, the insert silently fails: The update and any subsequent queries in the same transaction continue but no triples are updated (in that particular query). In addition the server log (`/var/rdf4j/server/logs/main.log` in `eclipse/rdf4j-workbench` docker run) shows:
```
[ERROR] ... [repositories/test123] We don't actually support adding a binding. newObj : "value2"
```

### Expected Behavior

Multiple `VALUES` clauses should not cause any issues in an `INSERT .. WHERE`

### Steps To Reproduce

1. Create a test repository
2. Run the following SPARQL UPDATE queries against it:
    ```sparql
    PREFIX ex: <http://example.org/>

    INSERT DATA { ex:sub ex:somePred "value" . };

    INSERT { ?s ?newPred ?newObj }
    WHERE {
      # If one combines these into a single VALUES clause then it also works
      VALUES ?newPred { ex:somePred2 }
      VALUES ?newObj { "value2" }
      ?s ex:somePred [] .
    }
    ```
3. Two triples should be returned:
    ```sparql
    PREFIX ex: <http://example.org/>

    DESCRIBE ex:sub
    ```
    - Actual result: only `ex:sub ex:somePred "value"` is returned.

### Version

4.3.7

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

- Might be related to https://github.com/eclipse-rdf4j/rdf4j/issues/4646 and https://github.com/eclipse-rdf4j/rdf4j/pull/4670
- Works fine with previous major release (tested with `3.7.7`)

**Comment by hmottestad** [comment]
This PR should hopefully solve the issue: https://github.com/eclipse-rdf4j/rdf4j/pull/4816
