### ISSUE TITLE
Elasticsearch tests use to much memory when autoconfigured on my desktop/home server ;)

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse-rdf4j/rdf4j#4831]
### Current Behavior

Elasticsearch tests spin up a node asking for 32GB of heap space on my desktop.

### Expected Behavior

Use about 1g or less for the unit tests 

### Version

5.0.0-DEVELOP

### Are you interested in contributing a solution yourself?

Yes

### Anything else?

We can just set `<ES_JAVA_OPTS>${java.sec.mgr}</ES_JAVA_OPTS>` in the /core/sail/elasticsearch-store/pom.xml to limit the heap to 1gb. 1gb is the setting determined in the github actions.

**Comment by hmottestad** [comment]
I merged you PR, but maybe we should have the same fix on the main branch?
