### ISSUE TITLE
LMDB: Align benchmarks with NativeStore

### ISSUE THREAD

**Issue by kenwenzel** [eclipse-rdf4j/rdf4j#4896]
### Problem description

To make benchmark results comparable we should use the Same benchmarks for NativeStore and LmdbStore.

### Preferred solution

Adapt benchmarks of NativeStore

### Are you interested in contributing a solution yourself?

None

### Alternatives you've considered

Create a common module with benchmarks for MemoryStore, NativeStore and LmdbStore

**Comment by hmottestad** [comment]
About "Create a common module with benchmarks for MemoryStore, NativeStore and LmdbStore".

I like to run the benchmarks from IntelliJ and I like to be able to run a single benchmark method on a particular store. I found that using class inheritance can be a bit problematic with the JMH plugin in IntelliJ.

A simple thing we could do though is to have a module where we keep all the data and queries and maybe some helper methods.
