### ISSUE TITLE
MapDB3 based collection factory should provide a queue and set implementation

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse-rdf4j/rdf4j#4899]
### Problem description

[qEndpoint](https://github.com/the-qa-company/qEndpoint/issues/349) has an issue where a path query triggers an out of memory exception. See the makeQuey and makeSet calls in [PathIteration](https://github.com/eclipse-rdf4j/rdf4j/blob/develop/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java). 

For the MapDb3 implementation we should be able to [add a queue](https://github.com/eclipse-rdf4j/rdf4j/blob/3996cd843dbd9b65f130df4839fb627755c1595e/core/collection-factory/mapdb3/src/main/java/org/eclipse/rdf4j/collection/factory/mapdb/MapDb3CollectionFactory.java#L175) that spills to disk.

### Preferred solution

Implement a java.util.Queue wrapper for a mapdb3 QueuLong that should be able to work here.

### Are you interested in contributing a solution yourself?

Yes

### Anything else?

Spilling to disk might make existing queries much slower. Perhaps take a much higher switch point from in memory to mapdb then the MemoryTillSizeXSet default.

**Comment by kenwenzel** [comment]
Do you think it makes sense to consider an LMDB-based persistent data structure?
I've added a PersistentSet to the LmdbStore module.

**Comment by JervenBolleman** [comment]
An lmdb based collection factory is still in my would like to do list.

**Comment by JervenBolleman** [comment]
MapDb3 QueueLong is undocumented and does not work like I assumed. Have a simple wrapper around a map where head and tail are maintained as keys.
