### ISSUE TITLE
Improve Shacl performance for large datasets

### ISSUE THREAD

**Issue by ElenaKurilina** [eclipse-rdf4j/rdf4j#4900]
### Problem description

When running SHACL validation on large datasets (5M triples) we've noticed that it takes up to 10 minutes to run a simple SHACL rule. 

### Preferred solution

Debugging showed that validation itself takes seconds and majority of the time is spend on operation:  `hasStatement(null, null, null, false);`  which is called 6 times in `ShaclSailConnection` and `ConnectionHelper` classes. 
5 calls can be simplified/avoided:
1. Avoid loading entire dataset into memory:
```java
hasStatement(null, null, null, false); // actually force a transaction to start 
// it has 3 calls and all can be replaced with:
hasStatement(dummyIRI, dummyIRI, dummyIRI, false); // actually force a transaction to start 
```
2. Can be removed as it's never used:
https://github.com/eclipse-rdf4j/rdf4j/blob/1ac18bfd4db81c69f8eff4cd3895d814b3f440a6/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java#L890 

3. Can be removed as  it's already set in the `begin`
 https://github.com/eclipse-rdf4j/rdf4j/blob/1ac18bfd4db81c69f8eff4cd3895d814b3f440a6/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java#L972 

### Are you interested in contributing a solution yourself?

Yes

**Comment by hmottestad** [comment]
You might be interested in testing out the ShaclValdiator class. This is an experimental class meant to allow you to run validation on data in an existing store. https://github.com/eclipse-rdf4j/rdf4j/blob/main/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java

**Comment by hmottestad** [comment]
Btw. `hasStatement(null,null,null)` shouldn't load more than a single statement into memory.

**Comment by ElenaKurilina** [comment]
> Btw. `hasStatement(null,null,null)` shouldn't load more than a single statement into memory.

Good point. It was our custom Sail specific. I was relaying on default impl that call `getStatement(null,null,null)` that returns all data.

**Comment by hmottestad** [comment]
Are you able to override that with your own, more optimized, implementation? Does that improve performance for you?

**Comment by hmottestad** [comment]
I'm closing this issue since it seems that the underlying problem is with your custom Sail implementation and I'm assuming that you've managed to fix it.

**Comment by hmottestad** [comment]
```
	default boolean hasStatement(Resource subj, IRI pred, Value obj, boolean includeInferred, Resource... contexts)
			throws SailException {

		try (CloseableIteration<? extends Statement> stIter = getStatements(subj, pred, obj,
				includeInferred, contexts)) {
			return stIter.hasNext();
		}

	}
```

Btw. The default implementation only calls hasNext() once, which shouldn't really cause all the data from the store to be loaded into memory.
