### ISSUE TITLE
Rio JSON LD Jackson core/databind dependency problem

### ISSUE THREAD

**Issue by vorburger** [eclipse-rdf4j/rdf4j#4907]
### Current Behavior

[Here](https://github.com/enola-dev/enola/pull/495/files), I'm depending on `rdf4j-rio:rdf4j-rio-jsonld` (version `5.0.0-M2`, but I think this problem affects `4.3.9` as well; haven't tested).

My `RdfTest` fails like this:

```java
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at org.eclipse.rdf4j.rio.jsonld.JSONLDWriter.endRDF(JSONLDWriter.java:163)
        at org.eclipse.rdf4j.rio.Rio.write(Rio.java:653)
        at org.eclipse.rdf4j.rio.Rio.write(Rio.java:629)
        at org.eclipse.rdf4j.rio.Rio.write(Rio.java:549)
        at dev.enola.rdf.RdfWriterConverter.convertInto(RdfWriterConverter.java:45)
        at dev.enola.rdf.RdfTest.check(RdfTest.java:89)
        at dev.enola.rdf.RdfTest.testRDF(RdfTest.java:83)
        ... 23 trimmed
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 31 more
```

The workaround is to manually add `com.fasterxml.jackson.core:jackson-databind:2.13.5` to one's project.

### Expected Behavior

It should work without having to manually fiddle with dependencies...

### Steps To Reproduce

Clone my project and remove the `com.fasterxml.jackson.core:jackson-databind:2.13.5` and you can reproduce it.

### Version

5.0.0-M2

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

My project uses https://bazel.build instead and it's theoretically possible Bazel is interpreting some <optional> dependency differently than Maven or Gradle.

**Comment by vorburger** [comment]
> My project uses https://bazel.build/ instead and it's theoretically possible Bazel is interpreting some dependency differently than Maven or Gradle.

Actually, strike that - I doubt that's the cause. Because `rdf4j-rio-jsonld` only [declares a dependency](https://github.com/eclipse-rdf4j/rdf4j/blob/2306c8b5b3f1d333e1259bb72ea1841b521c9deb/core/rio/jsonld/pom.xml#L61) on `jackson-core`, not `jackson-databind`, so this does seem odd, no?

It may will be some dependency mess bug ultimately more rooted in the "upstream" https://github.com/jsonld-java/jsonld-java/tree/master than here, of course - but I thought I would still make a start here, first.

**Comment by hmottestad** [comment]
I think this might be due to the jsonld module importing the query module as a test dependency, which contains databind.

Btw. RDF4J 5.0.0 will hopefully use Titanium JSON-LD, which doesn't use jackson.

**Comment by hmottestad** [comment]
@vorburger I'm trying to track down the cause of this issue and I see that jsonld-java depends on jackson-databind, so rdf4j-rio-jsonld should include this transitively. Any chance you can provide a minimal example project that reproduces the bug?

**Comment by vorburger** [comment]
> Btw. RDF4J 5.0.0 will hopefully use Titanium JSON-LD, which doesn't use jackson.

Good to know! FYI [I'm on 5.0.0-M2](https://github.com/enola-dev/enola/blob/ac5d6caddfaaa1b1ba2d5c8d945296d0e5691870/WORKSPACE.bazel#L25), and happy to upgrade to try it.

> I'm trying to track down the cause of this issue and I see that jsonld-java depends on jackson-databind, so rdf4j-rio-jsonld should include this transitively. Any chance you can provide a minimal example project that reproduces the bug?

Thank You! But as my project uses https://bazel.build/ instead and it's theoretically possible Bazel is interpreting some dependency differently than Maven or Gradle. I doubt you have any interest in tracking down a potentially Bazel specific problem. As I've been able to locally solve the problem, unless you want to further dig into this for other reason, let's perhaps just _close as not planned?_ Fine for me!
