### ISSUE TITLE
Backport critical fixes of LmdbStore to 4.x.x

### ISSUE THREAD

**Issue by kenwenzel** [eclipse-rdf4j/rdf4j#4971]
### Current Behavior

Critical fixes of the LmdbStore where only merged in develop and need to be backported to 4.x.x

### Expected Behavior

Cherry-pick required fixes and merge them to main.

### Version

4.3.11

### Are you interested in contributing a solution yourself?

Yes

**Comment by hmottestad** [comment]
@kenwenzel Are you still planning on backporting to 4.3.x?

**Comment by kenwenzel** [comment]
@hmottestad I don't think it is worth the time. We should focus on getting it stable within 5.x.x.

**Comment by hmottestad** [comment]
Sounds good!
