### ISSUE TITLE
LMDB should resize map based on how full it is

### ISSUE THREAD

**Issue by hmottestad** [eclipse-rdf4j/rdf4j#5014]
Calculate how full an LMDB map is as a percentage and trigger resizing once it exceeds a certain level, ex. 80%.

**Comment by hmottestad** [comment]
The existing logic resizes the map only whenever the next write operation will exceed the size of the map. This seems to work ok on Linux, but not on MacOS. On MacOS the LMDB Store will randomly throw a "MDB_BAD_TXN: Transaction must abort, has a child, or is invalid" error when under a high concurrent write load.

**Comment by kenwenzel** [comment]
If using this logic is then `requiredSize` needed at all?

**Comment by hmottestad** [comment]
Only if requiredSize is considerably bigger. Maybe a massive literal?
