### ISSUE TITLE
LMDB Store should cache IDs of common IRIs

### ISSUE THREAD

**Issue by hmottestad** [eclipse-rdf4j/rdf4j#5016]
Common IRIs, such as those in the w3c namespace, should have their IDs cache separately from other values since there are a limited number of these IRIs.

**Comment by kenwenzel** [comment]
Does this have really an Impact?

**Comment by hmottestad** [comment]
Fairly minor in my benchmarks. If you think it's too complicated then we can still remove it before releasing 5.0.0.
