### ISSUE TITLE
LMDB throwing java.lang.NoClassDefFoundError: org/mapdb/DBException on workbench: Explore >> Types invocation

### ISSUE THREAD

**Issue by nguyenm100** [eclipse-rdf4j/rdf4j#5055]
### Current Behavior

when you select Explore>>Types from workbench while a LMDB repo is open, an exception is thrown.

Type Exception Report

Message Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/mapdb/DBException

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.eclipse.rdf4j.repository.http.HTTPQueryEvaluationException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/mapdb/DBException
	org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:55)
	org.eclipse.rdf4j.workbench.commands.TypesServlet.service(TypesServlet.java:32)
	org.eclipse.rdf4j.workbench.base.TupleServlet.service(TupleServlet.java:55)
	org.eclipse.rdf4j.workbench.base.TupleServlet.service(TupleServlet.java:48)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:100)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:100)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:214)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:136)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:111)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:119)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:64)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:56)
Root Cause

org.eclipse.rdf4j.repository.RepositoryException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/mapdb/DBException
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1095)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1029)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:782)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:677)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:377)
	org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:52)
	org.eclipse.rdf4j.workbench.commands.TypesServlet.service(TypesServlet.java:32)
	org.eclipse.rdf4j.workbench.base.TupleServlet.service(TupleServlet.java:55)
	org.eclipse.rdf4j.workbench.base.TupleServlet.service(TupleServlet.java:48)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:100)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:100)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:214)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:136)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:111)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:119)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:64)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:56)
Note The full stack trace of the root cause is available in the server logs.

### Expected Behavior

no exception thrown

### Steps To Reproduce

WSL docker but we see it on linux too

Create a LMDB repo
add some triples
select workbench: Explore >> Types

get exception above

### Version

5.0

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by hmottestad** [comment]
@JervenBolleman Any idea what's going on?

**Comment by JervenBolleman** [comment]
@hmottestad first thought is that the jar of the updated mapdb is maybe named differently and therefore not being included in a war? I can only look at it tomorrow when coming back from a conference.

**Comment by nguyenm100** [comment]
does not occur with memory store.  
does occur with native store

**Comment by hmottestad** [comment]
@nguyenm100 Any chance you were using federation?

**Comment by hmottestad** [comment]
@JervenBolleman The rdf4j-tools-federation (e.g. FedX) still uses the old mapdb 1.0 based collection factory. Maybe there are conflicts due to that.

**Comment by nguyenm100** [comment]
not using federation.  was able to repro from wars from SDK as well as running 5.0 docker image.  actually, you don't have to load any triples at all.  just create native or lmdb repo and hit explore>>types from workbench

**Comment by hmottestad** [comment]
> not using federation.  was able to repro from wars from SDK as well as running 5.0 docker image.  actually, you don't have to load any triples at all.  just create native or lmdb repo and hit explore>>types from workbench

Would really appreciate if you or someone on your team had time to help flesh out our workbench test coverage. We've recently started using Playwright. It seems like the recommended tool over Cypress.

https://github.com/eclipse-rdf4j/rdf4j/blob/main/e2e/tests/workbench.spec.js

**Comment by nguyenm100** [comment]
will try and help.  team is busy trying to figure out if we can store a few billion triples with lmdb as well as replication.

**Comment by hmottestad** [comment]
If LMDB works with a few billion triples for you I would love to hear your experience and what setup you have! I'm sure @kenwenzel would also be interested.

**Comment by nguyenm100** [comment]
for sure.  been mostly focused on replication so far so haven't had time to dig into the guts of lmdb impl yet.  our rocksdb impl from Halyard days has ~3.5B triples so we know rdb can do it.  @kenwenzel do you have a design doc for your impl of lmdb by chance?

**Comment by JervenBolleman** [comment]
@hmottestad  your hunch about Mapdb 1+3 being in use at the same time was right.
