### ISSUE TITLE
Allow Child Sails to Benefit from `AbstractSailConnection`'s Buffering Scheme

### ISSUE THREAD

**Issue by benherber** [eclipse-rdf4j/rdf4j#5210]
### Problem description

`AbstractSailConnection` manages a lot of concurrency and buffering for implementing sails; however, when it goes to flush the buffer, it does so one triple at a time instead of allowing the implementing sail to flush the buffer itself. This causes the implementing sail to either have to pay a possible higher write cost since the writes are decoupled from each other or implement buffering itself which is counterintuitive to the expressed design of the parent class.

### Preferred solution

Ideally I would like just to be handed a `Collection<Statement>` that I can write to storage media en masse similar to how the snapshot store works. For backwards compatibility it can default to the existing implementation. The sail implementation being made is incompatible with how snapshot store is designed for a few reasons I won't get into. It has proven just much easier to extend from `AbstractSailConnection` instead for what I'm trying to do.

### Are you interested in contributing a solution yourself?

Yes

### Alternatives you've considered

I looked into a few solutions such as overriding methods in `AbstractSailConnection` but ran into concurrency issues since child sails don't have access to all the internals. I also experimented with my own buffer scheme in the child sail, but ended up just reimplementing what was in `AbstractSailConnection` more-or-less.

**Comment by nguyenm100** [comment]
@hmottestad can we get some feedback on this when you get a sec? we'd prefer not having to fork internally where possible. tx
